In [3]:
arr = []

Any[]

In [4]:
push!(arr, 1)

1-element Vector{Any}:
 1

In [5]:
push!(arr, 2,3,4,5)

5-element Vector{Any}:
 1
 2
 3
 4
 5

In [6]:
brr = copy(arr)

5-element Vector{Any}:
 1
 2
 3
 4
 5

In [8]:
arr[2] = 3

3

In [9]:
arr

5-element Vector{Any}:
 1
 3
 3
 4
 5

In [10]:
brr

5-element Vector{Any}:
 1
 2
 3
 4
 5

In [11]:
 crr = @views arr

5-element Vector{Any}:
 1
 3
 3
 4
 5

In [12]:
crr 

5-element Vector{Any}:
 1
 3
 3
 4
 5

In [13]:
arr[3] = 4

4

In [14]:
arr

5-element Vector{Any}:
 1
 3
 4
 4
 5

In [15]:
crr

5-element Vector{Any}:
 1
 3
 4
 4
 5

In [16]:
a = [1 2 3 4 5]

1×5 Matrix{Int64}:
 1  2  3  4  5

In [17]:
append!(a,[2])

LoadError: MethodError: no method matching append!(::Matrix{Int64}, ::Vector{Int64})

You might have used a 2d row vector where a 1d column vector was required.
Note the difference between 1d column vector [1,2,3] and 2d row vector [1 2 3].
You can convert to a column vector with the vec() function.
Closest candidates are:
  append!(::BitVector, ::Any) at ~/julia-1.7.3/share/julia/base/bitarray.jl:782
  append!(::Vector, ::AbstractVector) at ~/julia-1.7.3/share/julia/base/array.jl:1042
  append!(::AbstractVector, ::Any) at ~/julia-1.7.3/share/julia/base/array.jl:1050
  ...

In [18]:
a = [1,2,3,4,5]

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [19]:
append!(a, [2])

6-element Vector{Int64}:
 1
 2
 3
 4
 5
 2

Test regarding append and push with loop iteration:

In [8]:
x = []
y = []

Any[]

In [9]:
for i = 1:10
    push!(x,i)
end
x

10-element Vector{Any}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [10]:
for i in 1:10
    append!(y,[i]);
end
y

10-element Vector{Any}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

Array types

In [14]:
x = Array{Int}(undef,1)

1-element Vector{Int64}:
 0

In [15]:
x[1] = 10

10

In [16]:
push!(x, 1)

2-element Vector{Int64}:
 10
  1

In [17]:
push!(x, 1.2)

LoadError: InexactError: Int64(1.2)

In [18]:
push!(x, round(1.2))

3-element Vector{Int64}:
 10
  1
  1

In [19]:
x = Array{AbstractFloat}(undef, 1)

1-element Vector{AbstractFloat}:
 #undef

In [20]:
x[1] = 10

10

In [21]:
x

1-element Vector{AbstractFloat}:
 10.0

In [22]:
x = Array{Float64}(undef, 2,3)

2×3 Matrix{Float64}:
 2.3342e-313   2.122e-314    3.18299e-313
 2.75859e-313  2.97079e-313  3.60739e-313

In [23]:
x = zeros(2,3)

2×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [24]:
x = ones(2,3)

2×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [27]:
x = fill(2.0,2,3)

2×3 Matrix{Float64}:
 2.0  2.0  2.0
 2.0  2.0  2.0

In [29]:
x = fill(2,2,3)

2×3 Matrix{Int64}:
 2  2  2
 2  2  2

Pre-allocating array: better to know how many elements are you dealing with instead of append of push them into an array.

In [30]:
 z = zeros(10)

10-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [31]:
y = []

Any[]

Range

In [34]:
r = range(1,20, length = 10)
println(r, " ", typeof(r)) 

1.0:2.111111111111111:20.0 StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}


In [35]:
u = 1:2:20
println(u, " ", typeof(u))

1:2:19 StepRange{Int64, Int64}


In [36]:
z = zeros(3,4)

3×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [37]:
println(size(z))

(3, 4)


In [38]:
println(size(z,1))

3


In [39]:
println(size(z,2))

4


List comprehension 

In [42]:
l = [x for x in 1:20]

20-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20

In [43]:
l_even = [x%2 ==0 for x in 1:20]

20-element Vector{Bool}:
 0
 1
 0
 1
 0
 1
 0
 1
 0
 1
 0
 1
 0
 1
 0
 1
 0
 1
 0
 1

In [45]:
z = zeros(3,4)
println(z)

[0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0]


In [46]:
display(z)

3×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0