Loop

In [2]:
for i in 1:5
    println(i)
end

1
2
3
4
5


In [11]:
i = 0

while i < 5 
    println(i)
    #global i += 1
    i += 1
end

0
1
2
3
4


In [16]:
z = zeros(3,4)

for c in 1:size(z,2) # Remember Julia is column dominant
    for r in 1:size(z,1)
        z[r,c] += c
    end
end

display(z)

3×4 Matrix{Float64}:
 1.0  2.0  3.0  4.0
 1.0  2.0  3.0  4.0
 1.0  2.0  3.0  4.0

In [18]:
z = zeros(3,4)

for c in 1:size(z,2) # Remember Julia is column dominant
    for r in 1:size(z,1)
        z[r,c] += r
    end
end

display(z)

3×4 Matrix{Float64}:
 1.0  1.0  1.0  1.0
 2.0  2.0  2.0  2.0
 3.0  3.0  3.0  3.0

In [20]:
z = zeros(4,4)

for c in 1:size(z,2) # Remember Julia is column dominant
    for r in 1:size(z,1)
        z[r,c] += c +r 
    end
end

display(z)

4×4 Matrix{Float64}:
 2.0  3.0  4.0  5.0
 3.0  4.0  5.0  6.0
 4.0  5.0  6.0  7.0
 5.0  6.0  7.0  8.0